### ISSUE TITLE
Monsters teleport around the board

### ISSUE THREAD

**Issue by spirotris** [spirotris/sipi18-group1project2#15]
https://github.com/spirotris/sipi18-group1project2/blob/b21375ea9e0cb679f234ea3f06ecc13c74e87e0a/src/game/Levels.java#L59

This should include a check to make sure the monster only moves +-1 tile from within it's current position. And use the setX/setY inherited from Point.java for moving monsters otherwise the monsters saved in your ArrayList are just overwritten and there's no way to track monster locations once they've moved once.

**Comment by ohrling** [comment]
Oh, we're only moving them one step? Didn't know that! 🙂
Do we need to keep track of them? Enlighten me on why on slack!
