### ISSUE TITLE
Creates a new object every time getPoint is called!

### ISSUE THREAD

**Issue by spirotris** [spirotris/sipi18-group1project2#6]
https://github.com/spirotris/sipi18-group1project2/blob/47d8c70aea8b5a671288df945c3c7d62679f7cb8/src/game/Point.java#L28

**Comment by spirotris** [comment]
If a board is 20x20 that's 400 points, if we run the game at 30 fps down the line that's 12000 new objects per second if we draw the board by calling getPoint for each tile.
Any reason for not using: `return this;` ?

**Comment by Marcizz** [comment]
Glömde att ta det i stället. Du kan ändra det. Har inte tid att göra det idag

**Comment by Marcizz** [comment]
This has been fixed.
